services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ML_ENGINE_URL=http://ml-engine:8000
      - DATABASE_URL=file:./dev.db
      - GITHUB_TOKEN=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
      - GROQ_API_KEY=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
      - NEXT_PUBLIC_GITHUB_OWNER=oceankesarwani
      - NEXT_PUBLIC_GITHUB_REPO=Cafe-website
      - GITHUB_WEBHOOK_SECRET=CommitGuard_Super_Secret_123
    depends_on:
      - ml-engine
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules

  ml-engine:
    build:
      context: ml-engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml-engine:/app
      # Cache downloaded models
      - huggingface-cache:/root/.cache/huggingface
      - sentence-transformers-cache:/root/.cache/torch

volumes:
  huggingface-cache:
  sentence-transformers-cache:
